### ISSUE TITLE
Infografía: Ciclo de vida de un software.  Fernando Miguel López.

### ISSUE THREAD

**Issue by Ferch0419** [SistemasTecTlaxiaco/infografia-Ferch0419#2]
[CICLO DE VIDA DE UN SOFTWARE_FERNANDO MIGUEL LÓPEZ.pdf](https://github.com/SistemasTecTlaxiaco/infografia-Ferch0419/files/7157546/CICLO.DE.VIDA.DE.UN.SOFTWARE_FERNANDO.MIGUEL.LOPEZ.pdf)

**Comment by Band-hi** [comment]
Calificación: 21 puntos
 - Atractiva y muy visual
 - Información clara y concisa
 - Muy buen trabajo 👍🏾

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
